### ISSUE TITLE
38 bug

### ISSUE THREAD

**Issue by brk1864** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#15]
![img_20150515_180655](https://cloud.githubusercontent.com/assets/12281058/7655623/525d7c6a-fb2d-11e4-9d5e-8f7cf347b6a1.JPG)

**Comment by RedstoneGunMade** [comment]
@brk1864 they said that today they´ll fix

**Comment by jv110** [comment]
@btk1864 working for me. Are you sure you used the last commit?

**Comment by jv110** [comment]
*@brk1864

**Comment by brk1864** [comment]
@jv110 Sure.I was downloaded it a hour ago.
@RedstoneGunMade okey im waiting

**Comment by jv110** [comment]
@brk1864 oops, I forgot to push my changes to fix this; thats why it only works for me. Pull request made to fix it, but in the while try GitHub.com/jv110/MrCrayfishFurnitureMod-MCPE

**Comment by brk1864** [comment]
İ ll check it out

**Comment by byteandahalf** [comment]
@brk1864 I just merged the pull request to fix this

**Comment by brk1864** [comment]
@byteandahalf its working but when i try use the doorbell its crashing!

**Comment by jv110** [comment]
@brk1864 Sorry, will fix it (again)

**Comment by brk1864** [comment]
@jv110 no problem but i didnt try your codes i trying the @byteandahalf s code.

**Comment by jv110** [comment]
@brk1864 The one who added Cabinets and Doorbells was me.

**Comment by brk1864** [comment]
@jv110 ohhh sure my bad.i cant understand github yet.sorry.you are good modder.
