### ISSUE TITLE
Doorbells can't be rotated

### ISSUE THREAD

**Issue by byteandahalf** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#19]
Accidentally pressed entre before finishing typing...

**Comment by byteandahalf** [comment]
I keep trying to fix this but I'm way too tired to focus and do it right.. I'll fix it tomorrow.
ZZZzzzzzz

**Comment by jv110** [comment]
You should close this.

**Comment by DjZis** [comment]
How do you test this mod?

**Comment by DjZis** [comment]
@jv110 I sent to all issues so you can see my comment! Well, can you tell me please?

**Comment by DjZis** [comment]
@jv110 @byteandahalf Could you tell me please how I can test this mod?

**Comment by CrazyWolf23** [comment]
@MrCrayfish This issue is fixed, shouldn't you close this because it might confuse newcomers.
