### ISSUE TITLE
No one looks at this Repo anymore

### ISSUE THREAD

**Issue by jv110** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#25]
Just noticed both @byteandahalf and @MrCrayfish haven't commited in quite a long time and all PRs are being ignored.

**Comment by minecraftmuse3** [comment]
Yeah, why @byteandahalf @MrCrayfish ?

**Comment by Koolman12** [comment]
Idk

**Comment by Koolman12** [comment]
Today @CrazyWolf23 Makes the Computer and Printer

**Comment by Koolman12** [comment]
@My

**Comment by CrazyWolf23** [comment]
@jv110 @minecraftmuse3 @Koolman12 I Know Im Thinking We Should Work Together to finish the addon, then send a "PR" when were done.

**Comment by DatDopeBro** [comment]
Guess they've given up

**Comment by MrCrayfish** [comment]
We are still working on it. I've been working on some furniture privately, and haven't pushed it yet.
