### ISSUE TITLE
Counter rendering bug.

### ISSUE THREAD

**Issue by brk1864** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#26]
There is some bugs with counter rendering.
![screenshot_2015-06-01-23-13-09](https://cloud.githubusercontent.com/assets/12281058/7922315/fb57a2b2-08b3-11e5-862b-7dede048e831.png)
![screenshot_2015-06-01-23-13-16](https://cloud.githubusercontent.com/assets/12281058/7922319/07b325ae-08b4-11e5-980b-b30a9cc23c37.png)

**Comment by jv110** [comment]
It's not a bug - I'm just horrible with counter rendering.

**Comment by jv110** [comment]
And when porting the code, I didn't understand anything about counter's tile detection and rendering
Result: Dumb shitty rendering

**Comment by CrazyWolf23** [comment]
@jv110 @brk1864 I can try and fix that when I get home if that's ok.

**Comment by Koolman12** [comment]
@CrazyWolf23 Send me the computer update plz

**Comment by Koolman12** [comment]
And the new kitchen update

**Comment by CrazyWolf23** [comment]
@Koolman12 Sorry Mr.Crayfish regected my oven update, I'll start work on computers and fix counter tops later, I'm eating at McD's! yay!

**Comment by Koolman12** [comment]
oh ok

**Comment by MrCrayfish** [comment]
I will fix up the rendering conditions.

**Comment by CrazyWolf23** [comment]
@MrCrayfish what can I add to help?

**Comment by Koolman12** [comment]
Send me the update

**Comment by CrazyWolf23** [comment]
@Koolman12 all the update is is mine but without the oven, Lolz!

**Comment by CrazyWolf23** [comment]
@Koolman12 and I haven't added the computer yet.

**Comment by Koolman12** [comment]
I mean the new kitchen update with the blender

**Comment by Koolman12** [comment]
And Fridge

**Comment by brk1864** [comment]
@MrCrayfish okay im waiting.and are furnitures will have functions like tv,oven,microwave ?

**Comment by CrazyWolf23** [comment]
@brk1864 @Koolman12 I Plan on helping adding GUI and functions so yea maybe. And there isn't no blender and fridge yet, I don't think. Lol brb let me check.

**Comment by jv110** [comment]
@CrazyWolf23 what? I don't understand you, please speak correctly

**Comment by brk1864** [comment]
@CrazyWolf23 maybe huh? But if they havent function.the mod is so bad and useless.

**Comment by CrazyWolf23** [comment]
@brk1864 sorry, I'm not in charge of the mod, I'm just here to try and help. It's up to @MrCrayfish and 
@byteandahalf to add functions or blocks to the actual thing it's self.

**Comment by CrazyWolf23** [comment]
And @jv110 I was talking to @Koolman12 saying there is no blender or fridge in the addon yet.

**Comment by RedstoneGunMade** [comment]
@CrazyWolf23 you can been active all the days in twitter?! I need to talk with u!

**Comment by MrCrayfish** [comment]
@brk1864 You need to get off GitHub. It's people like you who annoy developers "Blah blah blah why isn't this added yet, update the mod. it dumb". Understand what IN DEVELOPMENT means before you complain about features not being added yet.

**Comment by CrazyWolf23** [comment]
@MrCrayfish What can i help with, i am very good at block rendering and adding, and items, and more.

**Comment by MrCrayfish** [comment]
@CrazyWolf23 Any furniture that isn't added?

**Comment by brk1864** [comment]
@MrCrayfish wow keep calm dude.i understand development.i just said if furnitures will dont have function the mod will doesnt same with PC version.im fan of you and byteandahalf.i like coding,moding so i like your works.i guess i misunderstood so im sorry and sorry for my english.

**Comment by brk1864** [comment]
@MrCrayfish woow dude keep calm.i guess i misunderstood.i can understand development.its very hard.but i just (want) said if mod is finish and if furnitures havent function its dont like PC version.i like coding,moding its hard.so i like your mod and byteandhalfs mod.you are working for us.im fan of you im fan of byteandhalf.im sorry if i misunderstood.and sorry if my english is bad.

**Comment by MrCrayfish** [comment]
Fixed the counter rendering in the latest patch :)
