### ISSUE TITLE
okay Good But =( !!!!

### ISSUE THREAD

**Issue by FanOfZhouwei** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#32]
No more updates :( I wish I have a computer :/ but plss keep updating MrCrayfish we all want your mod I'm happy when your mod Is ported in mcpe but too few but good job but pls keep updating =( =) thanks Hope you reply

**Comment by skullkeeper94** [comment]
Sorry I'm not MrCrayfish but you have to understand that, as he's porting his mod to MCPE, he's also working on the PC version. So you must give him time and please be patient. :)

**Comment by Koolman12** [comment]
Send DA update

**Comment by RedstoneGunMade** [comment]
@Koolman12 can you stop asking? not makes sence, and you have to compile it yourself.

**Comment by skullkeeper94** [comment]
Please be patient. If you want updates so bad why don't you help code? (Not @RedstoneGunMade ).

**Comment by FanOfZhouwei** [comment]
Okay So sorry <3
