### ISSUE TITLE
AIDE give errors

### ISSUE THREAD

**Issue by brk1864** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#33]
![screenshot_2015-07-20-11-29-14](https://cloud.githubusercontent.com/assets/12281058/8772184/9b1e4384-2ed2-11e5-8ee5-fff06f8ce8c2.png)

**Comment by skullkeeper94** [comment]
I know why and I fixed this. I currently do not have permission to upload the code. But I can tell you how to fix it. What you need to do it open OvenTile.cpp and go to when you find the letter F. Now you should see numbers. Add .0 to the end of the numbers to fix :)

**Comment by brk1864** [comment]
When? Because i really want test cookie jar.

**Comment by CrazyWolf23** [comment]
Just change <uses-sdk android::minSdkVersion="9"> to <uses-sdk android::minSdkVersion="14">

**Comment by CrazyWolf23** [comment]
@brk1864  Hope I Helped ;)

**Comment by CrazyWolf23** [comment]
Just change <uses-sdk android::minSdkVersion="9"> to <uses-sdk android::minSdkVersion="14"> in androidManifest.xml

**Comment by skullkeeper94** [comment]
I don't know. It will be whenever he adds my code. You can contact him on Twitter to add my code.

**Comment by skullkeeper94** [comment]
I can tell you how to fix it. (If you want)

**Comment by CrazyWolf23** [comment]
Dude just change the 9 to a 14 in androidManifest.xml

**Comment by jv110** [comment]
@CrazyWolf23's solution doesn't fix the problem, but instead just fixes a warning, and warning don't  affect building.

**Comment by brk1864** [comment]
@skullkeeper94 i want

**Comment by skullkeeper94** [comment]
@jv110 that's what I meant. Sorry if I was unclear. I have pull request out.

**Comment by skullkeeper94** [comment]
Also, @CrazyWolf23 that won't help. He needs to add .0 to the end of the 1F (and others) in OvenTile.cpp

**Comment by skullkeeper94** [comment]
Also, @CrazyWolf23 I removed your collision helper because it caused errors (for me). So I'll put it back once I can figure it out (don't get angry ) :(

**Comment by skullkeeper94** [comment]
:) everything is fixed for your errors. (I think. Please issue them if there are still errors).

**Comment by CrazyWolf23** [comment]
Just trying, @jv110 it usually fixes it for me.

**Comment by CrazyWolf23** [comment]
But I built the addon and it worked fine

**Comment by skullkeeper94** [comment]
He won't accept my fixes. :(
