### ISSUE TITLE
0.12.1 BETA

### ISSUE THREAD

**Issue by skullkeeper94** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#41]
Needs to be updated. I've been trying for a while but I get errors (as seen on my Twitter). If I or anyone else SUCCESSFULLY ports this to MCPE 0.12.1 then we can get back to adding blocks, items, and eventually GUI and toilet flushing/farting!

**Comment by byteandahalf** [comment]
I'll update it to 12.1 when the full version comes out.
