### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by minecraftmuse3** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#44]
In the repo it says "Pocket Edition of MrCrayfish's Funriture Mod for MCPE" when it should say "Pocket Edition of MrCrayfish's **Furniture** Mod for MCPE". I know this is a small issue but it's an issue just the same :)

**Comment by byteandahalf** [comment]
Apparently having write access to a repo still doesn't allow me to change the repo info.. Leave it to Cray

**Comment by minecraftmuse3** [comment]
@byteandahalf Haha lol

**Comment by byteandahalf** [comment]
Oh cool, be fixed it. Closing.
