### ISSUE TITLE
Update 0.14

### ISSUE THREAD

**Issue by TheLuckyCoder** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#52]
Can you update the mod to 0.14.0?

**Comment by MrCrayfish** [comment]
7 years later 😂 Yeah, this mod has been abandoned.

**Comment by TheLuckyCoder** [comment]
Too bad, I was really looking forward to playing it on 0.14.0😂😂

**Comment by malucard** [comment]
I remember adding a bunch of blocks to this mod when I was, what, 11? I'm still on the contributor list... They were fun times
