### ISSUE TITLE
Help my doorbell moves when pressed XD

### ISSUE THREAD

**Issue by Lady92** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#56]
right okay I've got a super weird glitch with the  doorbell with the mr cray fish furniture 1.11.2 minecraft mod. It shows the back when pressed but functions normally. Anyway to fix this???? Got the screenshots below.

![screenshot_182](https://user-images.githubusercontent.com/28394865/27917904-456ed264-6265-11e7-9eaa-0148aafb1e0a.png)
![screenshot_181](https://user-images.githubusercontent.com/28394865/27917911-4a6c2028-6265-11e7-98b4-0fd1b26301e7.png)

**Comment by skullkeeper94** [comment]
Is this the PC version? Or do you have split controls on with a zooned in screenshot? .-.

**Comment by Lady92** [comment]
Yeah it's the windows 10 pc version

**Comment by CrazyWolfy23** [comment]
The mod version your looking for is here: https://github.com/MrCrayfish/MrCrayfishFurnitureMod

**Comment by Lady92** [comment]
Is this the fix???

**Comment by CrazyWolfy23** [comment]
No, that is where you need to open the issue, this is the port for the android port, https://github.com/MrCrayfish/MrCrayfishFurnitureMod this is the link for the pc version your using, please open the issue there. Thank you. <3
