### ISSUE TITLE
Cant compile!

### ISSUE THREAD

**Issue by brk1864** [MrCrayfish/MrCrayfishFurnitureMod-MCPE#7]
If its my bad sorry.But i cant compiling this with AİDE its give 21 error.Can you share the apk please?
![screenshot_2015-05-06-22-55-07](https://cloud.githubusercontent.com/assets/12281058/7502214/fe47a9a2-f442-11e4-856e-1f43bf128fb7.png)

**Comment by jv110** [comment]
I fixed it in my pull request. And i think you may just wait, theyre refactoring the mod

**Comment by brk1864** [comment]
But i cant wait i want just test can you send me link?

**Comment by jv110** [comment]
Well, you can add a "_id" variable to StoneTableTile and WoodenTableTile (wooden is 200 and stone is 201) and a "_woodId" and "_stoneId" variables to TableTile (same IDs). It cant compile because those were missing.

**Comment by byteandahalf** [comment]
You need to build an older commit.

**Comment by MrCrayfish** [comment]
This has been fixed now :)

**Comment by brk1864** [comment]
Thanks.You are really good coders.

**Comment by byteandahalf** [comment]
Thanks man

**Comment by brk1864** [comment]
No problem.I dont wait MCPE DEVS more time.Im waiting your works.But i cant see doorbell and cabinet.How we can get them?

**Comment by jv110** [comment]
in my fork

**Comment by jv110** [comment]
however its using an old version of this, ill update later

**Comment by brk1864** [comment]
Can you show me how i get this ?

**Comment by byteandahalf** [comment]
@jv110 Don't update until after I push my refactors later today or tomorrow

**Comment by jv110** [comment]
Ok
